name: impresiones digitales 2
favicon: null
layout_spectrum: 0.9504455705173314
typography_spectrum: 0.657433450454846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3906927886418998
  lightness: 0.18923435569740832
  saturation: 0.8035415548365563
  rhythmicContrast: 0.9168394745793194
purpose: []
